baseURL = "https://critoracy.github.io/academis-demo/"
locale  = "en-US"
title   = "Academis Demo"

[taxonomies]
  tag    = "tags"
  author = "autori"

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel   = 3

[outputs]
  home     = ["HTML", "RSS"]
  section  = ["HTML", "RSS"]
  page     = ["HTML"]
  taxonomy = ["HTML"]
  term     = ["HTML"]

[module]
  [[module.imports]]
    path = "github.com/critoracy/Academis"
