[[main]]
  name   = "Articles"
  url    = "/articles/"
  weight = 10

[[main]]
  name   = "Announcements"
  url    = "/announcements/"
  weight = 20

[[main]]
  name   = "Personal"
  url    = "/personal/"
  weight = 30

[[main]]
  name   = "CV"
  url    = "/cv/"
  weight = 40

[[main]]
  name   = "Book"
  url    = "/book/"
  weight = 50
