[[main]]
  name   = "Articles"
  url    = "/articles/"
  weight = 10

[[main]]
  name   = "Announcements"
  url    = "/announcements/"
  weight = 20

[[main]]
  name   = "Book"
  url    = "/book/"
  weight = 30
